# These defaults can be overridden in parameters.yml
parameters:
    toran_config_file: %kernel.root_dir%/toran/config.yml
    toran_cache_dir: %kernel.root_dir%/toran/cache
    toran_scheme: http
    toran_web_dir: %kernel.root_dir%/../web
    toran_http_port: 80
    toran_https_port: 443
    session_save_path: %kernel.cache_dir%/sessions

    composer_home: %kernel.root_dir%/toran/composer
    composer_cache_dir: %kernel.root_dir%/toran/composer/cache
